### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by shapkarin** [scanf/xiyo.imba#5]
I want to add url validation but found an error: `relation "urls" does not exist`
Looks like it's not enough only to execute the provided script or I'm doing something wrong.

So after I execute the script I got that log:
```
CREATE DATABASE
ALTER ROLE
ALTER ROLE
ALTER ROLE
GRANT
psql:init-db.psql:15: ERROR:  relation "urls" already exists
```

**Comment by aalemayhu** [comment]
I might have omitted something from the README file. I will take look later this week, but feel free to open a pull request if you figure it out.

Thanks.

**Comment by shapkarin** [comment]
huh, time is the main problem... I will try to find it too

**Comment by aalemayhu** [comment]
Fixed in https://github.com/scanf/xiyo.imba/pull/3

**Comment by shapkarin** [comment]
@scanf thanks. But /create is 500 now at prod. Maybe it's the same issue that I had locally..

**Comment by aalemayhu** [comment]
Maybe, I pushed a fix. Can you pull from master and see if you can reproduce? Thanks.

**Comment by shapkarin** [comment]
@scanf, sure, I will have a look todays evening. Prod is fine now, thanks

**Comment by shapkarin** [comment]
@scanf still get `error: relation "urls" does not exist` tried to drop bd but that not helps. Not sure why that happens, I will also try to instigate.
